//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PocketIRC.rc
//
#define IDR_MENUBAR                     101
#define IDD_OPTIONS                     101
#define IDD_OPTIONS_SERVER              102
#define IDB_TOOLBAR                     107
#define IDR_STATUSMENU                  108
#define IDR_CHANNELMENU                 109
#define IDR_QUERYMENU                   110
#define IDI_APP                         111
#define IDD_OPTIONS_IDENT               112
#define IDD_OPTIONS_FORMAT              113
#define IDD_OPTIONS_DISPLAY             114
#define IDR_EDITMENU                    116
#define IDD_OPTIONS_ABOUT               118
#define IDD_CHOOSECOLOR                 119
#define IDD_CHOOSECOLOR_MINI            120
#define IDR_OFFCHANNELMENU              121
#define IDR_CHANNELUSERMENU             125
#define IDR_DCCMENU                     126
#define IDD_DCCLIST                     127
#define IDR_URLMENU                     128
#define IDR_DCCCHATMENU                 129
#define IDR_DCCLISTMENU                 130
#define IDD_OPTIONS_DCC                 131
#define IDD_OPTIONS_CHANNELS            132
#define IDD_CHANNELS_LIST               132
#define IDR_MENU1                       133
#define IDR_FAVCHANMENU                 133
#define IDD_CHANNELS                    134
#define IDD_CHANNELS_FAVOURITES         135
#define IDR_CHANLISTMENU                135
#define IDC_OPTIONS_NICKNAME            1000
#define IDC_OPTIONS_REALNAME            1001
#define IDC_OPTIONS_SERVERNAME          1002
#define IDC_OPTIONS_REMOVESERVER        1005
#define IDC_OPTIONS_SERVERPORT          1007
#define IDC_IDENT_ENABLE                1008
#define IDC_IDENT_USERNAME              1009
#define IDC_IDENT_PORT                  1010
#define IDC_FORMAT_EVENT                1011
#define IDC_FORMAT_STRING               1012
#define IDC_FORMAT_ENABLE               1013
#define IDC_FORMAT_RESET                1014
#define IDC_FORMAT_RESETALL             1015
#define IDC_OPTIONS_SERVERPASS          1016
#define IDC_DISPLAY_BACKGROUND          1018
#define IDC_DISPLAY_BROWSE              1019
#define IDC_DISPLAY_USEFULLSCREEN       1020
#define IDC_DISPLAY_CLOSENOTHIDE        1021
#define IDC_OPTIONS_TAB                 1022
#define IDC_DISPLAY_BACKALIGNTOP        1023
#define IDC_DISPLAY_BACKALIGNBOTTOM     1024
#define IDC_OPTIONS_QUITMSG             1026
#define IDC_FORMAT_STRIPINCOMING        1027
#define IDC_DISPLAY_STRIPINCOMING       1027
#define IDC_FORMAT_STRIPALL             1028
#define IDC_DISPLAY_STRIPALL            1028
#define IDC_FORMAT_TEXTCOLOR            1029
#define IDC_FORMAT_BACKCOLOR            1030
#define IDC_FORMAT_EXAMPLE              1031
#define IDC_FORMAT_FONT                 1034
#define IDC_FORMAT_FONTSIZE_SPIN        1037
#define IDC_FORMAT_FONTSIZE             1038
#define IDC_CHOOSECOLOR_RED             1043
#define IDC_CHOOSECOLOR_GREEN           1044
#define IDC_CHOOSECOLOR_BLUE            1045
#define IDC_SPIN1                       1046
#define IDC_CHOOSECOLOR_RED_SPIN        1046
#define IDC_SPIN2                       1047
#define IDC_CHOOSECOLOR_GREEN_SPIN      1047
#define IDC_SPIN3                       1048
#define IDC_CHOOSECOLOR_BLUE_SPIN       1048
#define IDC_CHOOSECOLOR_NEW             1049
#define IDC_CHOOSECOLOR_OLD             1050
#define IDC_CHOOSECOLOR_DEF             1051
#define IDC_CHOOSECOLOR_DEF1            1051
#define IDC_CHOOSECOLOR_DEF2            1052
#define IDC_CHOOSECOLOR_DEF3            1053
#define IDC_CHOOSECOLOR_DEF4            1054
#define IDC_CHOOSECOLOR_DEF5            1055
#define IDC_CHOOSECOLOR_DEF6            1056
#define IDC_CHOOSECOLOR_DEF7            1057
#define IDC_CHOOSECOLOR_DEF8            1058
#define IDC_CHOOSECOLOR_DEF9            1059
#define IDC_CHOOSECOLOR_DEF10           1060
#define IDC_CHOOSECOLOR_DEF11           1061
#define IDC_CHOOSECOLOR_DEF12           1062
#define IDC_CHOOSECOLOR_DEF13           1063
#define IDC_CHOOSECOLOR_DEF14           1064
#define IDC_CHOOSECOLOR_DEF15           1065
#define IDC_CHOOSECOLOR_DEF16           1066
#define IDC_ABOOT_REGCODE               1069
#define IDC_ABOOT_VERSION               1070
#define IDC_DCCLIST_USER                1071
#define IDC_DCCLIST_CHAT                1072
#define IDC_DCCLIST_SEND                1073
#define IDC_DCCLIST_ACCEPT              1074
#define IDC_DCCLIST_CLOSE               1075
#define IDC_DCCLIST_CLOSEALL            1076
#define IDC_DCCLIST_LIST                1077
#define IDC_DCCLIST_CLEAR               1078
#define IDC_DCC_USELOCALIP              1078
#define IDC_DCC_USEREMOTEIP             1079
#define IDC_DCC_USECUSTOMIP             1080
#define IDC_DCC_CUSTOMIP                1081
#define IDC_DCC_LOCALIP                 1082
#define IDC_DCC_REMOTEIP                1083
#define IDC_DCC_FIRSTPORT               1084
#define IDC_DCC_LASTPORT                1085
#define IDC_DCC_IGNORESEND              1086
#define IDC_DCC_IGNORECHAT              1087
#define IDC_CHECK1                      1088
#define IDC_CHANNELS_AUTOJOIN           1088
#define IDC_DISPLAY_TIMESTAMP           1088
#define IDC_CHANNELS_LIST               1089
#define IDC_CHANNELS_FAVOURITES_LIST    1089
#define IDC_CHANNELS_KEY                1090
#define IDC_CHANNELS_FAVOURITES_KEY     1090
#define IDC_BUTTON1                     1091
#define IDC_CHANNELS_SETKEY             1091
#define IDC_CHANNELS_FAVOURITES_SETKEY  1091
#define IDC_EDIT1                       1092
#define IDC_CHANNELS_NAME               1092
#define IDC_                            1092
#define IDC_CHANNELS_LIST_MINUSERS      1092
#define IDC_CHANNELS_TAB                1095
#define IDC_CHANNELS_LIST_REFRESH       1096
#define IDC_CHANNELS_LIST_LIST          1098
#define IDC_OPTIONS_VSCROLL             1100
#define IDC_OPTIONS_PANE                1101
#define IDC_CHANNELS_VSCROLL            1102
#define IDC_CHANNELS_LIST_COUNT         1104
#define ID_IRC                          40001
#define IDS_CAP_IRC                     40003
#define ID_IRC_EXIT                     40004
#define IDS_CAP_MENUITEM40005           40006
#define ID_IRC_OPTIONS                  40007
#define ID_IRC_CONNECT                  40008
#define ID_SAY                          40009
#define IDS_CAP_SAY                     40011
#define ID_MENUITEM40020                40020
#define ID_STATUS                       40021
#define IDS_CAP_STATUS                  40023
#define ID_STATUS_JOIN                  40024
#define ID_CHANNEL                      40025
#define IDS_CAP_CHANNEL                 40027
#define ID_CHANNEL_SAY                  40028
#define ID_QUERY                        40029
#define IDS_CAP_QUERY                   40031
#define ID_QUERY_SAY                    40032
#define ID_QUERY_ACT                    40034
#define ID_QUERY_CLOSE                  40035
#define ID_QUERY_NOTICE                 40036
#define ID_QUERY_WHOIS                  40037
#define ID_QUERY_PING                   40038
#define ID_CHANNEL_ACT                  40039
#define ID_CHANNEL_NOTICE               40040
#define ID_CHANNEL_KICK                 40041
#define ID_CHANNEL_MODE                 40042
#define ID_CHANNEL_TOPIC                40043
#define ID_CHANNEL_PART                 40044
#define ID_STATUS_QUERY                 40045
#define ID_STATUS_QUIT                  40046
#define ID_STATUS_RAW                   40047
#define ID_STATUS_WHOIS                 40048
#define ID_STATUS_PING                  40049
#define ID_STATUS_NICK                  40050
#define ID_IRC_VIEW_HIDE                40051
#define ID_IRC_VIEW_FULLSCREEN          40052
#define ID_EDIT                         40053
#define IDS_CAP_EDIT                    40055
#define ID_EDIT_CUT                     40056
#define ID_EDIT_COPY                    40057
#define ID_EDIT_PASTE                   40058
#define ID_EDIT_DELETE                  40059
#define ID_EDIT_SELECTALL               40060
#define ID_EDIT_UNDO                    40061
#define ID_EDIT_COLOR_CHOOSE            40062
#define ID_EDIT_COLOR_BOLD              40063
#define ID_EDIT_COLOR_UNDERLINE         40064
#define ID_EDIT_COLOR_NORMAL            40065
#define ID_EDIT_COLOR_REMOVEALL         40066
#define ID_EDIT_CLEAR                   40067
#define ID_IRC_HELP                     40068
#define ID_CHANNEL_SHOWUSERLIST         40069
#define ID_QUERY_INVITE                 40070
#define ID_QUERY_CTCP                   40071
#define ID_QUERY_QUERY                  40072
#define ID_CHANNEL_JOIN                 40075
#define ID_STATUS_MODESELF              40079
#define ID_CHANNEL_INVITE               40080
#define ID_CHANNELUSER                  40081
#define IDS_CAP_CHANNELUSER             40083
#define ID_CHANNELUSER_VOICE            40084
#define ID_CHANNELUSER_DEVOICE          40085
#define ID_CHANNELUSER_OP               40086
#define ID_CHANNELUSER_DEOP             40087
#define ID_CHANNELUSER_KICK             40088
#define ID_CHANNELUSER_BAN              40089
#define ID_CHANNELUSER_KICKBAN          40090
#define ID_CHANNELUSER_QUERY            40091
#define ID_CHANNELUSER_WHOIS            40092
#define ID_STATUS_NICKSERV              40093
#define ID_DCC                          40094
#define IDS_CAP_DCC                     40096
#define ID_DCC_CLOSEDCCLIST             40097
#define ID_IRC_VIEW_DCCLIST             40098
#define ID_URL                          40099
#define IDS_CAP_URL                     40101
#define ID_URL_BROWSE                   40102
#define ID_DCCCHAT                      40103
#define IDS_CAP_DCCCHAT                 40105
#define ID_DCCCHAT_SAY                  40106
#define ID_DCCCHAT_ACT                  40107
#define ID_DCCCHAT_CLOSE                40108
#define ID_DCCLIST                      40109
#define IDS_CAP_DCCLIST                 40111
#define ID_DCCLIST_ACCEPT               40112
#define ID_DCCLIST_CLOSE                40113
#define ID_DCCLIST_CLOSEALL             40114
#define ID_DCCLIST_CLEAR                40115
#define ID_QUERY_DCCCHAT                40116
#define ID_QUERY_DCCSEND                40117
#define ID_CHANNELUSER_DCCSEND          40118
#define ID_CHANNELUSER_DCCCHAT          40119
#define ID_DCCCHAT_DCCSEND              40120
#define ID_EDIT_COLOR_INVERSE           40121
#define ID_FAVOURITECHANNEL_AUTOJOINONCONNECT 40124
#define ID_FAVOURITECHANNEL_RENAME      40125
#define ID_FAVOURITECHANNEL_DELETE      40126
#define ID_FAVOURITECHANNEL_NEW         40127
#define ID_CHANNEL_FAVOURITECHANNEL     40128
#define ID_CHANNEL_AUTOJOINONCONNECT    40129
#define ID_IRC_CHANNELS                 40130
#define ID_STATUS_FAVOURITECHANNELS     40131
#define ID_IRC_CHANNELS40132            40132
#define ID_CHANNEL_REJOIN               40133
#define ID_FAVOURITECHANNEL_JOINNOW     40134
#define ID_CHANNELLIST_JOINNOW          40135
#define ID_CHANNELLIST_FAVOURITECHANNEL 40136
#define ID_CHANNELLIST_AUTOJOINONCONNECT 40137
#define ID_CHANNELLIST_CLEARLIST        40138
#define ID_IRC_CONTEXT                  65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40139
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
